APP_CONTEXT_PATH = ''
APP_NAME = 'app'

DEV_MODE = True

TEMPLATES_AUTO_RELOAD = True

SQLALCHEMY_DATABASE_URI = 'mysql+pymysql://root:@localhost/blue_blade_dev'
SQLALCHEMY_POOL_SIZE = 10
SQLALCHEMY_POOL_RECYCLE = 15
SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_ECHO = True
