APP_CONTEXT_PATH = ''
APP_NAME = 'app'

DEV_MODE = False
TEMPLATES_AUTO_RELOAD = False

SQLALCHEMY_DATABASE_URI = 'mysql+pymysql://root:@localhost/blue_blade_test'
SQLALCHEMY_POOL_SIZE = 10
SQLALCHEMY_POOL_RECYCLE = 15
SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_ECHO = False
